# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Brent and Skye Show
email:
description: >- # this means to ignore newlines until "baseurl:"
  A podcast about growing up ... but not too fast!
  After a 12-year hiatus, we're back and better than ever.
twitter_username: username
github_username: username
minimal_mistakes_skin: air
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /ep/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Chicago # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "The Brent and Skye Show!"
  avatar : "/assets/images/bas-logo-1024.png"
  bio    : "A podcast about growing up ... but not too fast! After a 12-year hiatus, we're back and better than ever."
  links:
    - label: "Email us!"
      icon: "far fa-fw fa-envelope"
      url: "mailto:brentandskye@gmail.com"
    - label: "Leave a message!"
      icon: "fas fa-fw fa-phone"
      url: "https://"
    - label: "Apple Podcasts"
      icon: "fas fa-fw fa-podcast"
      url: "https://"
    - label: "Spotify"
      icon: "fab fa-fw fa-spotify"
      url: "https://"
    - label: "Overcast"
      icon: "fas fa-fw fa-broadcast-tower"
      url: "https://"
    - label: "Google Podcasts"
      icon: "fab fa-fw fa-google"
      url: "https://"
    - label: "RSS"
      icon: "fas fa-fw fa-rss-square"
      url: "https://"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      show_date: true
      comments: true
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
